### PR TITLE
Add benchmark for valideer

### PR DESCRIPTION
**Pull request by gsakkis**
Added a new benchmark for [Valideer](https://github.com/podio/valideer), yet another validation library (Disclaimer: I am the main author). 

Despite the fact that high performance was not among valideer's goals and that it is a pure python package written ~7 years ago, it appears to be as fast as pydantic when the latter is compiled with Cython and 1.6x faster when not. Here are some benchmark results on python 3.6.7:
```
pydantic (cython)        best=15.165μs/iter  avg=15.842μs/iter  stdev=0.685μs/iter
valideer                 best=15.686μs/iter  avg=15.885μs/iter  stdev=0.219μs/iter
pydantic (pure python)   best=24.488μs/iter  avg=25.639μs/iter  stdev=0.815μs/iter
toasted-marshmallow      best=34.630μs/iter  avg=35.930μs/iter  stdev=1.627μs/iter
marshmallow              best=35.155μs/iter  avg=36.345μs/iter  stdev=1.453μs/iter
trafaret                 best=37.089μs/iter  avg=37.947μs/iter  stdev=1.109μs/iter
django-restful-framework best=157.965μs/iter avg=162.176μs/iter stdev=3.537μs/iter
```
Package versions:
- pydantic==0.30.1
- valideer==0.4.2
- toastedmarshmallow==2.15.2.post1
- marshmallow==2.19.5
- trafaret==1.2.0
- djangorestframework==3.10.0

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Thanks so much for this, sorry I haven't dealt with it. I'm going to defer further changes to benchmarks until after v1 (see #576), but after that I promise to deal with this.

Sorry again for the delay.

**Comment by gsakkis** [comment]
Sure no rush, thanks for the update.

**Comment by samuelcolvin** [comment]
I've merged master, and updated benchmarks. I'll merge this once tests pass.

valideer is still the fasted other than pydantic :-)

**Comment by gsakkis** [comment]
Great, thank you!

**Pull request merged**
