### PR TITLE
Adds stubs for BaseModel, validator, and conint

### PR DESCRIPTION
**Pull request by nathanielobrown**
This is just a start but it has `BaseModel` and `BaseModel` is the most important thing. No idea what's the best path here, but this is what I'm using for my project and I thought I'd get the ball rolling. Refer to issue #110 for dicsussion

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Maybe I'm missing something, but why can't we add this it the actual python source?

If it has to be in a pyi file that's fine, but I'm not clear.

**Comment by nathanielobrown** [comment]
I think the issue is that most people (or at least myself) realistically have to run mypy with `--ignore-missing-imports` and do not include their PYTHONPATH in their MYPYPATH. This means that none of the annotations in the pydantic codebase are used, and you need to provide some stub files that you place on your MYPYPATH that are used instead, which is what I've been doing. My idea is that at the very least we could share our stubs here for others to use, and maybe later add them to the typeshed.

Now on further inspection of the mypy docs, it appears maybe I should add my PYTHONPATH to my MYPYPATH and then use `--follow-imports=silent`, but I haven't tried that yet.

I'm still figuring all this stuff out and I definitely do not know what I'm doing. How would you ensure that your pydantic models are getting correctly type-checked by mypy if you hare pydantic in site-packages along with a bunch of other, un-annotated packages you are using as well?

**Comment by samuelcolvin** [comment]
Makes sense, can you update for the latest pydantic. Eg. Use dict not ordereddict, include create_model. 

Hoq do we add unit tests to make sure the stub stays up-to-date with the source?

**Comment by nathanielobrown** [comment]
Not sure about `create_model` as it is pretty dynamic. On keeping these up to date, perhaps we can use something like [monkeytype](http://monkeytype.readthedocs.io/en/latest/)? I was just trying it out and it didn't work out of the box using the tests for a few reasons but might be made to work.

**Comment by samuelcolvin** [comment]
Sorry I haven't dealt with this.

See aio-libs/aiohttp#1749 and the linked issues for an interesting discussion on this.

**Comment by samuelcolvin** [comment]
@nathanielobrown did you have any luck with `--follow-imports=silent`?

I'm still thinking about this but my impression is that mypy et. al. is still fairly bleeding edge and I don't really want another file to manually keep uptodate if I don't have to.

**Comment by samuelcolvin** [comment]
Closing this as mypy v.590 is released.

**Pull request closed without merging**
