### PR TITLE
add .gitattributes file

### PR DESCRIPTION
**Pull request by Kilo59**
Line ending differences can introduce an unnecessary amount of churn into the git history.
https://github.com/samuelcolvin/pydantic/pull/2434#pullrequestreview-632974755

Rather than spending time getting contributors to fix their git config or tooling to push the correct line ending; we can provide a `.gitattributes` file. This seems to be ~~one of~~ the currently accepted best way~~s~~ to handle this issue.
https://stackoverflow.com/a/10855862/6304433
https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

~~One thing that I have not yet done is a final [line endings re-normalization](
https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings). I want to make sure I can do that without rewriting the commit history to make it look like I'm taking credit for those code changes.~~
I applied it but it looks like the lines are all LF, so nothing to normalize 😄 .

## Change Summary

Merged a few of the templates from https://github.com/alexkaratarakis/gitattributes to provide thorough coverage for the types of files in this project.

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
*  ~~Documentation reflects the changes where applicable~~
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] final lined-ending normalization

### CODE REVIEW

**Comment by Kilo59** [comment]
This is failing on windows for py3.9
FAILED tests/test_hypothesis_plugin.py::test_can_construct_models_with_all_fields[MiscModel]
Is that expected?

```
mingw32-make: *** [Makefile:62: test] Error 1
Error: Process completed with exit code 1.
```

**Comment by PrettyWood** [comment]
@Kilo59 flaky test :/

**Comment by Kilo59** [comment]
> @Kilo59 flaky test :/
> Btw I don't understand the whole point. The diff in the mentioned review is due to leading whitespaces in md files, not trailing lines. The proof is that your PR doesn't change anything.

It looks to have both.
https://github.com/samuelcolvin/pydantic/pull/2434/files#r611134307

That code hasn't been merged yet.

But regardless it is occasionally an issue, and this should prevent anybody from having to deal with it in the future.

To the extent that people have bad feelings about `.gitattributes` files, it is usually related to line-ending changes in binary files. Here I've properly accounted for that.

**Comment by samuelcolvin** [comment]
I'm still a bit unclear on what this actually does.

Maybe it's because I don't work on windows?

But if it helps some people, I'm happy to merge it, can you just push again to make sure tests are passing.

Please update.

**Comment by samuelcolvin** [comment]
Hasn't been much need for this. Windows users can either manage their own line endings, or use a proper operating system :smile:

**Pull request closed without merging**
