### PR TITLE
Accept empty query/fragment URL parts

### PR DESCRIPTION
**Pull request by xavier**
## Change Summary

Fixes the URL validation to accept empty query or fragments.

## Related issue number

fix https://github.com/samuelcolvin/pydantic/issues/1807

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by xavier** [comment]
please review

**Comment by PrettyWood** [comment]
Hi @xavier and thanks for your contribution.
Your PR fixes https://github.com/samuelcolvin/pydantic/issues/1807 ;)
Please update the description accordingly

**Comment by xavier** [comment]
please review

**Comment by llgerard** [comment]
I am running into this too.

**Review by PrettyWood — APPROVED** [review]
Thank you 🙏

**Pull request merged**
