### PR TITLE
v1.7 patch (currently v1.7.3)

### LINKED ISSUE #2158: v1.7.3
@samuelcolvin To help us track them all, here are the fixes that should/could be in a v1.7.3

- [x] fix: ignore `__doc__` as valid private attribute #2091
- [x] Fixes a regression where Enum fields would not propagate keyword arguments to the schema #2109
- [x] fix: update all modified field values in `root_validator` when `validate_assignment` is on #2119
- [x] fix: support `underscore_attrs_are_private` with generic models #2139 
- [x] fix: set right default value for required (optional) fields #2143
- [x] Fix #2111: support pickle for built-in dataclasses #2114

### PR DESCRIPTION
**Pull request by samuelcolvin**
Fix #2158.

@PrettyWood are you happy with this? If so I'll release v1.7.3 asap.

### CODE REVIEW

**Comment by PrettyWood** [comment]
Hi @samuelcolvin 
Thanks for merging everything! I just double checked. LGTM!

**Comment by PrettyWood** [comment]
@samuelcolvin When running `test-fastapi`, the repo is cloned and dependencies are automatically added.
The issue with the CI is due to new resolver in `pip 20.3`. There are already plenty of issues on [the repo](https://github.com/pypa/pip/issues).
I guess we can:
- skip fastapi tests (not really smart imo)
- wait for `pip` to fix it (but how long will it take?) or `fastapi` to make changes in its deps
- pin `pip==20.2` (seems reasonable)
WDYT?

**Comment by samuelcolvin** [comment]
I've pinned pip

**Comment by samuelcolvin** [comment]
release is deploying now.

**Pull request merged**
