### PR TITLE
Dataclasses

### LINKED ISSUE #178: Python 3.7 dataclasses
I don't know if this is supposed to work. Would be nice. I can try to fix it if you propose the way.

```
@dataclasses.dataclass
class C(pydantic.BaseModel):
     i:int
c = C(1)
....
RecursionError: maximum recursion depth exceeded
```

### PR DESCRIPTION
**Pull request by samuelcolvin**
replaces #231, fixes #178.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
ready.

@Gaunt @Gr1N @pauleveritt please review and let me know if you see any problems, otherwise I'll merge and deploy in a couple of days.

**Comment by pauleveritt** [comment]
I just noticed ``@pydantic.dataclasses.dataclass(frozen=True)`` works as expected. Cool. Does it internally map to the "faux immutability" support?

**Comment by pauleveritt** [comment]
Models using dataclass don't have ``.copy()``, ``.json()``, ``dict()`` for https://pydantic-docs.helpmanual.io/#serialisation

**Comment by samuelcolvin** [comment]
> faux immutability

Yes

> Models using dataclass don't have .copy(), .json(), dict()

That's because they return vanilla dataclasses, I want to keep it like that. If you want the serialisation methods user normal models.

**Comment by Gr1N** [comment]
Awesome feature! LGTM!

**Pull request merged**
