### PR TITLE
Support dataclasses in pydantic_encoder

### PR DESCRIPTION
**Pull request by DanielOberg**
Please fill this in ->

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `HISTORY.rst` has been updated
  * if this is the first change since a release, please add a new section
  * include the issue number or this pull request number `#<number>`
  * include your github username `@<whomever>`

### CODE REVIEW

**Comment by drunkwcodes** [comment]
LGTM.
Could you add a test in `test_json.py` and fix the lint error?

**Comment by samuelcolvin** [comment]
Thanks for your contribution, but the template in PRs is there for a reason. Please respect it and complete the required tasks.

**Comment by samuelcolvin** [comment]
@DanielOberg are you ok to fix this?

**Comment by samuelcolvin** [comment]
I'm finishing this on #575.

**Pull request closed without merging**
