### PR TITLE
Add DRF Benchmark

### PR DESCRIPTION
**Pull request by mgu**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Awsome, thank you. What are the results?

**Comment by mgu** [comment]
trafaret   best=1.391s, avg=1.402s, stdev=0.013s
drf        best=6.006s, avg=6.153s, stdev=0.183s
pydantic   best=0.678s, avg=0.694s, stdev=0.014s

:)

**Comment by samuelcolvin** [comment]
wow, that's not great of drf. But having read its code in the past it, it does masses of checking that it's configured right and calls out to slow django standard methods.

I'll have a play with it later and merge.

**Comment by mgu** [comment]
ok, thanks

**Comment by samuelcolvin** [comment]
Looks good. I'm shocked by the performance gap.

I'll try to add a few more popular packages and then perhaps add a graph of relative performance to the docs.

**Comment by ybressler** [comment]
This PR is a top result for a google search on "Pydantic + DRF" >> perhaps we can create a ticket to describe the benchmark on Pydantic's documentation? Additionally, it would be helpful to have some guidance on how the frameworks compare to each other.

**Pull request merged**
