### PR TITLE
Support mypy 0.910 to 0.930 including CI tests

### PR DESCRIPTION
**Pull request by samuelcolvin**
Some cleanup from #3573, also stealing logic from #3572.

I normally don't think changing the versions of mypy which the plugin is compatible with would be a problem in a minor release, but since we've already made two beta release of v1.9, breaking mypy compatibility now would be ugly.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Right now, pypi is partially down, hence all the failures, see [here](https://twitter.com/samuel_colvin/status/1476257837890387979).

**Comment by samuelcolvin** [comment]
@christianbundy, @PrettyWood I'd love you feedback on this.

I still need to get tests passing once pypi is back up and add a change description.

**Review by christianbundy — APPROVED** [review]
Looks great to me.

**Comment by samuelcolvin** [comment]
LGTM. I'll merge tomorrow.

**Pull request merged**
