### PR TITLE
Run mypy test faster

### PR DESCRIPTION
**Pull request by MrMrRobat**
## Change Summary
Use `asyncio.subprocess` and some hacky stuff to run parametrized `test_mypy_result`

##### Master: `============================== 10 passed in 8.38s ==============================`

Not sure, if this results worth introduced hackery though, so it's ok if this won't be merged :) 

## Related issue number
https://github.com/samuelcolvin/pydantic/pull/2035#issuecomment-716448824

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by MrMrRobat** [comment]
Not sure what's wrong on windows: diffs look identical. 

@samuelcolvin, @dmontagu, do you have any Ideas?

**Comment by samuelcolvin** [comment]
Humm, I have no idea.

Is this really worth the effort?

**Comment by MrMrRobat** [comment]
I'm not sure, just was playing around to see if I could make theese tests run faster. 
Maybe it's worth opening issue in pytest repo (not necessairly for sake of solving this issue).

As for now, I don't have motivation right now to dig further, but it may change overtime. If you ok with hackiness introduced there, maybe someday I will find a fix, otherwise, you can close this PR.

**Comment by samuelcolvin** [comment]
Happy to leave it open for now.

**Comment by samuelcolvin** [comment]
actually I'm going to close this. The number of open PRs is stressing me out 😓.

Feel free to ask me to reopen it or create a new one if you want to continue.

**Pull request closed without merging**
