### PR TITLE
Update documentation (#162)

### PR DESCRIPTION
**Pull request by Gr1N**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Looks good, except we need a bit of discussion of how errors work and how they can be displayed to end users.

**Comment by Gr1N** [comment]
@samuelcolvin updated, check please

**Comment by samuelcolvin** [comment]
Looks good, I have some changes and improvements to the English, but that's probably better done in a separate PR.

**Comment by Gr1N** [comment]
Thanks!

**Comment by samuelcolvin** [comment]
#162

**Pull request merged**
