### PR TITLE
Add a frozenset type annotation to allowed_schemes on stricturl

### PR DESCRIPTION
**Pull request by Midnighter**
## Change Summary

I was recently using the `stricturl` field type and declared some constants for the allowed schemes. Semantically, it makes the most sense to me to use `frozenset`s for those constants. Thus I propose to extend the type annotation to include `FrozenSet[str]`.

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

Locally, the test suite fails for me with 

```
pydantic/main.py:367:5: C901 'BaseModel.__setattr__' is too complex (15)
```

but that's unrelated to my change.

### CODE REVIEW

**Review by PrettyWood — COMMENTED** [review]
LGTM!
For the local error on `make lint`, it's because you must be using python 3.7 version.
The check is done on the line with the decorator (l367) whereas with python 3.8 it's the decorated one that is (l369)
https://github.com/samuelcolvin/pydantic/blob/1a2791d4223ff1d18400432ef5d020ce6910aa4a/pydantic/main.py#L368-L369
We could probably just add a second `# noqa: C901` on l367 like it's done above
https://github.com/samuelcolvin/pydantic/blob/1a2791d4223ff1d18400432ef5d020ce6910aa4a/pydantic/main.py#L211-L212

**Comment by Midnighter** [comment]
You are correct. I had messed up something with my virtualenvs. Tests all pass in a fresh new 3.8 environment.

**Comment by samuelcolvin** [comment]
LGTM, please add a change description.

**Comment by Midnighter** [comment]
> LGTM, please add a change description.

Sorry, I already had this locally but failed to push it. It's in now.

**Review by PrettyWood — APPROVED** [review]
LGTM!

**Comment by samuelcolvin** [comment]
thanks a lot.

**Pull request merged**
