### PR TITLE
build(deps): bump mypy from 0.920 to 0.930

### PR DESCRIPTION
**Pull request by PrettyWood**
## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Looks good, can we add a change description?

Seems sad up introduce all those "type ignores", is that our fault or mypy's fault?

Does this need to be noted in the docs and/or marked as a breaking change?

**Comment by christianbundy** [comment]
> Does this need to be noted in the docs and/or marked as a breaking change?

Yes, the latest pydantic release supports mypy 0.910 but this drops support for mypy < 0.930. I think this change should be released in pydantic 2.0.0.

**Comment by samuelcolvin** [comment]
I think we just add a "breaking change" note in the changelog and go for it.

**Comment by christianbundy** [comment]
I would expect zero breaking changes between v1.8.2 and v1.9.0 -- does pydantic use semver, or some other versioning scheme?

**Comment by samuelcolvin** [comment]
Not strictly, see other releases.

> I would expect zero breaking changes between v1.8.2 and v1.9.0

Unfortunately that's not realistic, in pydantic or any other software.

**Comment by christianbundy** [comment]
Maybe I should’ve said “zero intentional breaking changes”. :~)

Could you help me understand the downside to releasing a new major version? IMO putting a “breaking change” like in the changelog for a minor version should raise a parsing error.

**Comment by samuelcolvin** [comment]
> Maybe I should’ve said “zero intentional breaking changes”. :~)

Ye, I agree with you that this would be a better approach.

I want to get v2 (with big changes to how validation and validators work) out in the new year. After that, I think we should move to strict semvar and more regular major releases.

**Comment by samuelcolvin** [comment]
I'm going to merge this and add a change description elsewhere.

**Pull request merged**
