### PR TITLE
Use __class__ attribute for 5% speed gain.

### PR DESCRIPTION
**Pull request by StephenBrown2**
## Change Summary

Updates https://github.com/samuelcolvin/pydantic/tree/use-class-attribute on top of current master. It isn't 2x faster, which may be why the branch hasn't been merged yet, but it is faster, about 5% on average, as demonstrated below (avg=117.592μs/iter on master vs avg=111.204μs/iter on use-class-attribute):

```
# On branch master
❯ BENCHMARK_REPEATS=100 make benchmark-pydantic
python benchmarks/run.py pydantic-only
                                pydantic time=0.674s, success=50.10%
                                ...
                                pydantic time=0.670s, success=50.10%
                                pydantic best=0.647s, avg=0.706s, stdev=0.111s

                                pydantic best=107.908μs/iter avg=117.592μs/iter stdev=18.569μs/iter version=1.4a1

❯ git checkout use-class-attribute
Switched to branch 'use-class-attribute'
Your branch is up to date with 'mine/use-class-attribute'.

❯ BENCHMARK_REPEATS=100 make benchmark-pydantic
python benchmarks/run.py pydantic-only
                                pydantic time=0.824s, success=50.10%
                                ...
                                pydantic time=0.660s, success=50.10%
                                pydantic best=0.637s, avg=0.667s, stdev=0.032s

                                pydantic best=106.111μs/iter avg=111.204μs/iter stdev=5.374μs/iter version=1.4a1
```

## Related issue number

None

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by samuelcolvin** [comment]
interesting, I couldn't get a confirmed improvement.

Did you compile pydantic for the benchmarks?

**Comment by StephenBrown2** [comment]
Yes, I got the same relative results after compiling (and recompiling):
```
❯ git checkout master && make clean build-cython benchmark-pydantic && git checkout use-class-attribute && make clean build-cython benchmark-pydantic
master:                 pydantic best=75.329μs/iter avg=85.574μs/iter stdev=11.919μs/iter version=1.4a1
use-class-attribute:    pydantic best=74.781μs/iter avg=81.755μs/iter stdev=8.646μs/iter version=1.4a1
```

**Comment by samuelcolvin** [comment]
@StephenBrown2 could you fix tests?

**Comment by StephenBrown2** [comment]
Tests fixed, but coverage went down. :-(

**Comment by samuelcolvin** [comment]
I think codecov is broken, I'll try and fix that and fix coverage later.

**Comment by StephenBrown2** [comment]
Coverage actually updated, no change.

**Pull request merged**
