### PR TITLE
Add dataclassesjson on benchmark

### PR DESCRIPTION
**Pull request by dutradda**
**NOTICE**: pydantic is currently pushing towards V1 release, 
see [issue 576](https://github.com/samuelcolvin/pydantic/issues/576). Changes not required to release version 1
may be be delayed until after version 1 is released. If your PR is a bugfix for v0.32, please base off and target the `v0.32.x` branch.

## Change Summary

Add the [dataclassesjson](/dutradda/dataclassesjson) library on benchmark

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.rst` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Thanks for the contribution.

There's an extra overhead to every new library added to the benchmarks. Perhaps the benchmarks should become a separate project outside pydantic, but while they're part of pydantic I want to limit the libraries included in benchmarks to those with significant usage (say >200 stars on github, for lack of a better metric, we could alternatively use number of downloads from pypi).

Therefore let's defer this until the library has gained significant adoption.

Sorry for the negative response and best of luck with the project.

**Comment by dutradda** [comment]
@samuelcolvin 
I think better you change the docs, because I "felt free" to submit more benchmarks, but there are restrictions that you not mentioned.

```
Feel free to submit more benchmarks or improve an existing one.
```
https://pydantic-docs.helpmanual.io/#benchmarks-tag

**Comment by samuelcolvin** [comment]
mea culpa, sorry about that, I'll update the docs.

**Comment by samuelcolvin** [comment]
done in #818

**Pull request closed without merging**
