### PR TITLE
test env_settings.py: Add lack of dotenv test

### PR DESCRIPTION
**Pull request by Alcolo47**
## Change Summary

env_settings.py is now 100% covered.

### CODE REVIEW

**Review by PrettyWood — COMMENTED** [review]
I don't understand. Pydantic has already 100% coverage. Can you explain what line exactly was not tested?

**Comment by Alcolo47** [comment]
> I don't understand. Pydantic has already 100% coverage. Can you explain what line exactly was not tested?

In my environment, in env_settings.py
```
    try:
        from dotenv import dotenv_values
    except ImportError as e:
        raise ImportError('python-dotenv is not installed, run `pip install pydantic[dotenv]`') from e
```
The `except ImportError` is not tested.
If optional packages are installed or not, coverage can change. This test fix this fluctuation.

I thank that CodeCov don't cover at 100% according to CodeCov report in my last MR.

When I launch `make testcov` my coverage is:
```
----------- coverage: platform linux, python 3.9.2-final-0 -----------
Name                             Stmts   Miss Branch BrPart     Cover
---------------------------------------------------------------------
pydantic/__init__.py                15      0      0      0   100.00%
pydantic/_hypothesis_plugin.py     122      0     46      0   100.00%
pydantic/annotated_types.py         12      1      8      1    90.00%
pydantic/class_validators.py       168      0    130      0   100.00%
pydantic/color.py                  190      0     85      0   100.00%
pydantic/dataclasses.py            100      0     46      0   100.00%
pydantic/datetime_parse.py         124      0     64      0   100.00%
pydantic/decorator.py              172      0     72      0   100.00%
pydantic/env_settings.py           126      2     54      0    98.89%
pydantic/error_wrappers.py          88      0     30      0   100.00%
pydantic/errors.py                 278      0      4      0   100.00%
pydantic/fields.py                 514      0    276      0   100.00%
pydantic/generics.py               121      0     69      0   100.00%
pydantic/json.py                    50      1     14      1    96.88%
pydantic/main.py                   522      2    241      0    99.74%
pydantic/mypy.py                   356      1    150      1    99.60%
pydantic/networks.py               271      3     68      1    98.82%
pydantic/parse.py                   36      0     20      0   100.00%
pydantic/schema.py                 421      0    228      0   100.00%
pydantic/tools.py                   29      0      4      0   100.00%
pydantic/types.py                  505      0     96      0   100.00%
pydantic/typing.py                 159     33     68      8    77.53%
pydantic/utils.py                  293      1    144      1    99.54%
pydantic/validators.py             419      0    188      0   100.00%
pydantic/version.py                 17      2      4      0    90.48%
---------------------------------------------------------------------
TOTAL                             5108     46   2109     13    99.04%
```

Non-cover codes are coming from:
- `except ImportError`
- `if sys.version_info < (3, x)`
- `if TYPE_CHECKING`

**Comment by PrettyWood** [comment]
Tests are run with and without extra deps in CI. Still not sure why you need to add this

**Comment by PrettyWood** [comment]
Tested here
https://github.com/samuelcolvin/pydantic/blob/master/tests/test_settings.py#L695-L704

**Pull request closed without merging**
