### PR TITLE
add strict_int config

### PR DESCRIPTION
**Pull request by amirfru**
## Change Summary

Add a global option `strict_int` to treat all `int` fields as strict

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable

* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by PrettyWood** [comment]
Where is the discussion? Or the linked PR welcome? Why not just use `StrictInt`? What about https://github.com/samuelcolvin/pydantic/issues/1098?
This PR will probably be closed

**Comment by amirfru** [comment]
Hi @PrettyWood, yes it is very-much related to #1098 , I really like this project but I really prefer not to add `StrictInt` (or any typing for that matter) if not needed. i.e. I have many configurations and delta-configuration files and I do not want to go over every single field and decide if it is an `int` or should actually be `float` but someone forgot to put a dot after the number.
Just want to let Pydantic to infer it by the initial input.
and I think that when someone tries to put a `float` in an `int` fields, it should raise an exception, this is the new added option.

**Comment by amirfru** [comment]
its just a micro PR which will make Pydantic much better for me

**Comment by amirfru** [comment]
Meanwhile I'm using [this](https://gist.github.com/samuelcolvin/714e75a74284696204de390a121b0da0) trick in-order to get roughly the same desired behavior

**Comment by PrettyWood** [comment]
> its just a micro PR which will make Pydantic much better for me

@amirfru Believe me a lot of people say this, me included 😄
But the goal of a library is to try to stay consistent and avoid having plenty of different settings that make it harder and harder to use but also maintain.
Tomorrow someone will come with a `strict_float` request and another one with `strict_str`...
This is why I reckon we should avoid "breaking the first window" and tackle the whole problem or not at all.
If a "strict mode" is added, we can probably make it configurable only for some types or some fields.
Your inputs on the "strict mode" issue are more than welcome to ensure the implementation will suit your needs 👍

**Comment by samuelcolvin** [comment]
@PrettyWood is correct here.

I'm afraid this will have to wait for a proper strict mode.

**Pull request closed without merging**
