### PR TITLE
Handle default_factory in constant_validator

### PR DESCRIPTION
**Pull request by adrienball**
## Change Summary

This PR allows to provide a value for model field which has a default factory, when the provided value matches the value generated by the factory.

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by adrienball** [comment]
please review

**Review by PrettyWood — COMMENTED** [review]
`const` is probably going to be removed soon as `Literal[...]` is now used to declare a value that can't be changed.
I don't understand the usecase of `default_factory` + `const`.

**Comment by samuelcolvin** [comment]
No response, closing.

**Comment by ClemDoum** [comment]
Actually even without the circular import the factory can be useful when objects reference each other in a circular way.
This works:
```python
def _my_class_name() -> str:
    return MyClass.name   # MyClass is defined at runtime but not yet at import time

class MyClassConfig(BaseModel):
    name: str = Field(default_factory=_my_class_name, const=True)
    
class MyClass:
    config_cls: MyClassConfig
    
    @classmethod
    @property
    def name(cls) -> str:
        cls.config_cls.name
```

whereas this fails:
```python
class MyClassConfig(BaseModel):
    # MyClass is not yet defined here, and you can't use a literal here either
    name: str = Field(default=MyClass.name, const=True)
    
class MyClass:
    config_cls: MyClassConfig
    
    @classmethod
    @property
    def name(cls) -> str:
        cls.config_cls.name
```

**Pull request closed without merging**
