### PR TITLE
Add strict_union Field feature for non-order affected unions.

### PR DESCRIPTION
**Pull request by aviramha**
## Change Summary

Add strict_union parameter to Field function - defaults to False. 
In case it's set to True and type is of Union, when validating it'll use the first subclass of a type, instead of just trying to validate against all. Unlike the regular validation, it wont accept int -> str or something similar.

## Related issue number

https://github.com/samuelcolvin/pydantic/issues/453

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [Will do after initial approval] Documentation reflects the changes where applicable
* [Will do after initial approval] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by aviramha** [comment]
I'm wondering what to do in case of typing hints inside a Union, for example:
`a: Union[Set[str], List[str]]`
if I do model(a=["123"] I'll get back {"123"}...

**Comment by samuelcolvin** [comment]
I'm not sure about this, I think #619 and #1423 would be better solutions.

@PrettyWood what do you think?

**Comment by PrettyWood** [comment]
@samuelcolvin I'm really torn with this issue.
On the one hand I completely agree the whole union behaviour should be improved and the linked issues are better solutions. But on the other hand we got so many issues about unions! (I think it's the most common issue on *pydantic*)
And every time we just answer "yes we know and we'll do something about it one day".
This will probably be tackled in v2, which won't be released anytime soon unfortunately (I hope 2021 🙏)
So I guess having a workaround behind a feature could be a nice spare wheel.

**Comment by samuelcolvin** [comment]
I think we have to wait for at least #619.

**Comment by samuelcolvin** [comment]
it's worth noting that #619 could be added without waiting for v2.

Also we could create a `StrictUnion` or `SmartUnion` which behaved more like #1423 without waiting for v2, then make it the default logic for v2.

**Pull request closed without merging**
