### PR TITLE
CentOS 7: `read_text(encoding='utf-8')`

### PR DESCRIPTION
**Pull request by hswong3i**
## Change Summary

With CentOS 7 Python 3.6, running install from source with pip failed:

    sudo podman run -ti --rm centos:7
    yum -y update
    yum -y install epel-release
    yum -y install git python3 python3-devel python3-pip python3-setuptools python3-wheel
    git clone https://github.com/samuelcolvin/pydantic.git
    cd pydantic
    pip3 install .

With following error message:

    [root@c99d0585636c pydantic]# pip3 install .
    Processing /pydantic
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-91v_ixvz-build/setup.py", line 62, in <module>
            history = (THIS_DIR / 'HISTORY.md').read_text()
          File "/usr/lib64/python3.6/pathlib.py", line 1197, in read_text
            return f.read()
          File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
            return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14648: ordinal not in range(128)

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-91v_ixvz-build/

This PR add the required `read_text(encoding='utf-8')` for `setup.py`.

Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by hswong3i** [comment]
please review

**Comment by samuelcolvin** [comment]
Fine by me, but support for python 3.6 had just been dropped, see #3605

**Comment by hswong3i** [comment]
Good idea for dropping Python 3.6 due to EOL, but I also found some else python lib facing similar issue with `read_text(encoding='utf-8')` as here, which they also apply similar fix for it, e.g.:
  * https://github.com/docker/docker-py/blob/master/setup.py#L44-L45
  * https://github.com/arrow-py/arrow/blob/master/setup.py#L6-L7
  * https://github.com/pyparsing/pyparsing/blob/master/setup.py#L16-L19

Adding this for preventing some edge cases should still be a good idea ;-)

**Comment by samuelcolvin** [comment]
Agreed, please add a change description.

**Comment by hswong3i** [comment]
Change description added :-)

**Comment by samuelcolvin** [comment]
thank you.

**Pull request merged**
