### PR TITLE
fix parse error of parse_date() and parse_datetime() when input is 0

### PR DESCRIPTION
**Pull request by YannLuo**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
thank you, please add change to `HISTORY.rst`

**Comment by samuelcolvin** [comment]
Easier for me to update history after merging on this occasion.

Thanks for the contribution.

**Comment by samuelcolvin** [comment]
I'll wait a couple of days to release in case any problems come out of the v0.8 release, but if you need this urgently let me know and I'll do a release more quickly.

**Comment by YannLuo** [comment]
I'm a newbie programmer and just testing my test case generator.
Feeling glad to contribute to this project :)

**Pull request merged**
