### PR TITLE
Change Union with None to Optional

### PR DESCRIPTION
**Pull request by hramezani**
## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by hramezani** [comment]
please review

**Comment by samuelcolvin** [comment]
Seems weird it was like that before.

Could this be a weird artifact of cython? 

Are there other cases where we didn't do it this way?

Is there anything in git blame to suggest these lines were edited at the same time?

If there's no specific reason and cython is happy, LGTM.

**Comment by hramezani** [comment]
> Could this be a weird artifact of cython?

 I have no idea

> Are there other cases where we didn't do it this way?

In `pydantic/color.py`, we have 

* `def parse_float_alpha(value: Union[None, str, float, int]) -> Optional[float]:`
* `def parse_hsl(h: str, h_units: str, s: str, l: str, alpha: Optional[float] = None) -> RGBA:`

in `parse_float_alpha` we have `value: Union[None, str, float, int]` and `Optional[float]` as return value.(why we didn't use `Optional` for return value :thinking: ?)

On the other hand, we have `Optional[float]` in `parse_hsl`.

Note: Both functions were added in the same commit(https://github.com/samuelcolvin/pydantic/commit/22f134475d8df84479239f37f68711fc569a05a9)
 
> Is there anything in git blame to suggest these lines were edited at the same time?
No, I couldn't find it.

**Comment by samuelcolvin** [comment]
Wait I had completely mis-read this, it seems you're suggestion switching:
1. from `Union[None, Foo, Bar]`
2. to `Optional[Union[Foo, Bar]]`

I think this is wrong, I think 1) is more correct.

Do you have any source that recommends this?

@PrettyWood do you have an opinion on this?

**Comment by hramezani** [comment]
I think `Optional[X] = Union[X, None]`. so `Optional[Union[Foo, Bar]] = Union[None, Union[Foo, Bar]]`. 
in theory `Union[None, Union[Foo, Bar]] = Union[None, Foo, Bar]`. but I am not sure how python considers that.

BTW, we can ignore the change if you think it may cause a problem.

**Comment by hramezani** [comment]
I find this from stackoverflow

> There is technically no difference between using Optional[] on a Union[], or just adding None to the Union[]. So Optional[Union[str, int]] and Union[str, int, None] are exactly the same thing.

https://stackoverflow.com/a/51710151/3465428

**Comment by samuelcolvin** [comment]
They're definitely the same, it's just semantics.

I prefer how it is now.

**Pull request closed without merging**
