### PR TITLE
Add MongoDB network data source name (DSN) schema

### PR DESCRIPTION
**Pull request by snosratiershad**
## Change Summary

Add MongoDB DSN schema to pydantic.networks and also fix something about Kafka DSN,
It's useful in project configuration, settings, handlers and etc.
## Related issue number

related to this [discussion](https://github.com/samuelcolvin/pydantic/discussions/3229)
## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by snosratiershad** [comment]
NOTE: this PR doesn't support "Replica Set" and "Sharded Cluster" deployment modes specific parts validations

**Comment by snosratiershad** [comment]
Please approve the workflow.

**Comment by snosratiershad** [comment]
Need to workflow approval...

**Comment by samuelcolvin** [comment]
I think this needs to be rebased, there's no work flow to approve currently

**Comment by snosratiershad** [comment]
just merged master into this PR after months, I don't know if it works or not with current changes, but seems like it's OK.

**Comment by samuelcolvin** [comment]
I've been working on pydantic v2, I'll try to get to this soon.

**Comment by samuelcolvin** [comment]
This is great, thank you so much.

**Pull request merged**
