### PR TITLE
Consistent __repr__ and __str__ methods for all types

### PR DESCRIPTION
**Pull request by samuelcolvin**
## Change Summary

Consistent `__repr__` and `__str__` method for all models, in general:
* `__str__` returns a human readable string representing the data the instances holds. Defined as something like "what you might show to an end user if you were lazy"
* `__repr__` is roughly `f'ClassName({str(self)})'`, except commas are used in separators to make 
 `eval(repr(m))` roughly equal to m

other changes:
* `__pretty__` method added to integrate with [python-devtools](https://python-devtools.helpmanual.io/)
* `display()` method on `SecretStr` and `SecretBytes` has been depreciated in favour of `str(s)
* (virtually unused and undocumented) `to_string()` method on `BaseModel` has been depreciated in favour of `str(model)`, devtools is a much better approach.

This is a bigger than I had hoped for during v1 betas, however users have done something seriously wrong if they're parsing the output of `str(x)` or `repr(x)` and I think this is much better than what went before.

This can't be merged until either all docs examples changed, or we setup an automatic way of generating the print output in examples (I'm going to work on this).

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I've looked but can't find any official (or quasi-official) guidance on what format or data should be used in `__repr__()` and `__str__()`. If there is any, a pointer would be very helpful.

Instead I looked a some big projects like numpy and django and did something simpler and sensible.

**Comment by dmontagu** [comment]
To make my suggestion more concrete:

Current form:
```python
    assert "<Model v=[<SubModel name='testing' count=4>]>" == repr(m)
```

Version currently proposed in this PR:
```python
  assert repr(m) == "<Model(v=[<SubModel(name='testing' count=4)>])>"
```

Version I'm proposing in the above comment:
```python
  assert repr(m) == "Model(v=[SubModel(name='testing', count=4)])"
```

**Comment by dmontagu** [comment]
My suggestion would be to handle `str` the same way, but using `str` rather than `repr` to render field values. So (with the changes to repr for `SecretStr`, which I think are right since it isn't eval-compatible) it would behave like this:

```python
from pydantic import SecretStr, BaseModel


class Model(BaseModel):
    secret: SecretStr


print(str(Model(secret='abc')))
# Model(secret=SecretStr('**********'))

print(repr(Model(secret='abc')))
# Model(secret=<SecretStr('**********')>)
```

**Comment by samuelcolvin** [comment]
I agree with everything except:

> My suggestion would be to handle str the same way, but using str rather than repr to render field values.

This is wrong IMHO:
1. `str(Model(str_value='foo bar'))`  would be `"Model(str_value=foo bar)"` which is at all clear - imagine a much longer string, or a sub-model with many members.
2. This is also not how other commonly used types work, eg. `str(['foo bar'])` is `"['foo bar']"`.

In other words: even though you're calling `str()` on the object, sub-items should use `repr()`

**Comment by dmontagu** [comment]
You were totally right about the str vs represent for arguments. 🤦‍♂️

**Comment by ashears** [comment]
Code quality improved in this PR IMO.

**Comment by ashears** [comment]
> Code quality improved in this PR IMO, all goodness

**Comment by dmontagu** [comment]
Looks good to me

**Pull request merged**
