### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by binderclip**
https://github.com/samuelcolvin/pydantic/issues/206

### CODE REVIEW

**Comment by samuelcolvin** [comment]
This seems to be failing.

**Comment by binderclip** [comment]
Hi @samuelcolvin , it seems that the errors are imported by the python environment change.

I have [a build](https://travis-ci.org/binderclip/pydantic/jobs/395836008) with the pydantic master code, falling with same error. 

If you have time, please take a look at the error msgs.
```
Build 1:
value = {'3', 1, 2}, result = [1, 2, '3']

Build 2:
E   ImportError: cannot import name '_TypingBase' from 'typing' (/opt/python/3.7-dev/lib/python3.7/typing.py)
```

https://travis-ci.org/samuelcolvin/pydantic/builds/395403583

**Comment by samuelcolvin** [comment]
Ok I'll look.

**Comment by Gr1N** [comment]
Got same issue with tests, fix can be found in my PR #208

**Comment by samuelcolvin** [comment]
Thank you so much.

**Pull request merged**
