### PR TITLE
docs: Remove Uber's Ludwig

### PR DESCRIPTION
**Pull request by q0w**
Seems like they switched to `marshmallow` recently

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
pydantic still listed as a requirement https://github.com/ludwig-ai/ludwig/blob/master/requirements_serve.txt

**Comment by q0w** [comment]
Not anymore:
https://github.com/ludwig-ai/ludwig/blob/master/requirements_serve.txt

**Comment by q0w** [comment]
please review

**Comment by samuelcolvin** [comment]
FastAPI has pydantic as a dependency, so I would argue (without looking in detail) that pydantic is still used.

**Comment by q0w** [comment]
FastAPI has pydantic as a dependency and can be listed there, but not Ludwig

**Comment by samuelcolvin** [comment]
I disagree. If you're using FastAPI, you're using pydantic whether with explicit imports and explicit pinned dependency or not.

**Pull request closed without merging**
