### PR TITLE
support self argument

### LINKED ISSUE #629: How to use a field called "self"
# Question
Is it possible to have a field on a model called "self"?
(Background to the question is JSON-API has links called "self", "related" etc.)

* Python version 3.7.3
* Pydantic version 0.29

```py
from pydantic import BaseModel

class Model(BaseModel):
    self: str

m = Model(self="some URL")
# TypeError: __init__() got multiple values for argument 'self'
```

I tried calling the field "self_" using an alias called "self"

```py
from pydantic import BaseModel, Schema

class Model(BaseModel):
    self_: str = Schema(alias="self")

m = Model(self="some URL")
# TypeError: __init__() got multiple values for argument 'self'
```

### PR DESCRIPTION
**Pull request by samuelcolvin**
fix #629

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [ ] ~~Documentation reflects the changes where applicable~~
* [x] `HISTORY.rst` has been updated
  * if this is the first change since a release, please add a new section
  * include the issue number or this pull request number `#<number>`
  * include your github username `@<whomever>`

### CODE REVIEW

**Comment by skaaptjop** [comment]
@samuelcolvin so that would work if 'self' is at the root of the dict but if it's nested it doesn't.
e.g.

```py
from pydantic import BaseModel

class Nested(BaseModel):
    self: str

class Model(BaseModel):
    nested: Nested

m = Model.parse_obj({"nested": {"self": "me"}})
#pydantic.error_wrappers.ValidationError: 1 validation error
#nested
# __init__() got multiple values for argument 'self' (type=type_error)
```

**Comment by skaaptjop** [comment]
That seems to do it.

**Comment by dgasmith** [comment]
Note that this breaks nested models that overload a BaseModel's `__init__`.

**Comment by samuelcolvin** [comment]
Humm, hadn't thought of that. 

Anything we can do? Or just add a note to the release notes.

**Comment by dgasmith** [comment]
If I understand the issue correctly, the first argument in the `__init__` should be renamed:

```
class MyClass:

    def __init__(self_model, self=5):
        self_model.self = self

a = MyClass(self=3)

print(a.self)
```

You could even to rename it to something like `pydantic_base_model_init` or something to ensure no collisions would occur.

I think supporting canonical init overloading is relatively important. The `@validator`s work really well for most cases, but complex cases where I need to share state before/after the BaseModel init and it starts to become a bit more clunky.

**Pull request merged**
