### PR TITLE
Bump Pydantic version to 1.9.0

### PR DESCRIPTION
**Pull request by christianbundy**
## Change Summary

Problem: There's been lots of work done on Pydantic since 1.8.2, and
there hasn't been a release cut for 1.9.0 yet.

Solution: Try to reduce maintainer load by following the '1.8.2 prep'
example to help with the 1.9.0 release.

## Related issue number

See-also: https://github.com/samuelcolvin/pydantic/pull/2780

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by christianbundy** [comment]
please review

**Comment by samuelcolvin** [comment]
Hi, I know I need to make a new release, but I don't think this helps. I need to go through a lot of PRs merge then, then make a new release.

Pydantic really is on my conscience, I know I need to find some time to fix it.

**Comment by christianbundy** [comment]
Thanks for the quick response — sorry if this isn’t helpful, is there anything I can do to help? Most of my open source maintenance has been in the JS/TS ecosystem but I have lots of empathy for how much time + energy releases take.

**Comment by samuelcolvin** [comment]
Honestly, probably the most useful thing is to review open PRs you think look important and say:

> I've tried this and it works well

Or

> I've tried this and the following things don't work...

**Comment by christianbundy** [comment]
Would you be open to releasing what we have now as an alpha or similar? I've tried using `master` and the only bug I hit was resolved by https://github.com/samuelcolvin/pydantic/pull/3324.

For context, my team is blocked from upgrading to 3.9.8 until we can upgrade Pydantic due to https://github.com/samuelcolvin/pydantic/issues/3423.

**Comment by samuelcolvin** [comment]
I'm working on it, see [this tweet](https://twitter.com/samuel_colvin/status/1467456649468256258)

**Pull request closed without merging**
