### PR TITLE
Adds `dataclass_transform` to dataclass

### LINKED ISSUE #4006: [Feature request] [VS Code] No auto complete when using pydantic.dataclasses.dataclass
# Feature request

Similar to the issue that #2721 solves, VS Code can't auto complete models constructor parameters when using `pydantic.dataclasses.dataclass`.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /tmp/hello-world/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
                     platform: Linux-5.10.105-1-MANJARO-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Example Code:
```python
import pydantic
from pydantic.dataclasses import dataclass

@dataclass
class Hello:
    n: int
    s: str

hello = Hello(n=1, s="a")
hello.n
```

VS Code:

https://user-images.githubusercontent.com/13181797/164987610-f6704c45-3afd-4b92-9a8a-b9addeb83dd9.mp4

# Workaround:
You can import python pure dataclass instead of pydantic's dataclass when type checking, as stated by @JosXa [here](https://github.com/microsoft/python-language-server/issues/1898#issuecomment-743645817):

```python
from pydantic.dataclasses import dataclass
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass as dataclass
```

### PR DESCRIPTION
**Pull request by giuliano-oliveira**
## Change Summary
This PR continues #2721 by adding `__dataclass_transform__` decorator to the pydantic dataclass decorator so that pyright can infer the `__init__` method as well as the instance attributes and types.

For more info about this decorator make sure to check out #2721.

## Related issue number

Fixes #4006
## Checklist

* [ ] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [X] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [X] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by giuliano-oliveira** [comment]
@samuelcolvin `make docs` aren't working in the current master branch, it seems the last two commits made it stopped working, don't know what to do here...

**Comment by samuelcolvin** [comment]
I'll look soon, might be after pycon though.

**Comment by giuliano-oliveira** [comment]
please review

**Comment by samuelcolvin** [comment]
this needs to be rebased from msater to fix CI.

**Pull request merged**
