### PR TITLE
Fix master

### PR DESCRIPTION
**Pull request by samuelcolvin**
Trying to fix master.

### CODE REVIEW

**Comment by MrMrRobat** [comment]
`validate_always` is getting set to `True` because of https://github.com/samuelcolvin/pydantic/commit/8aebba2c35007b848aceed2f8ae55fd7b4888ab6#diff-1ef405a6b5a2fa9f20ea7e1f92e4c38eR510 combined with https://github.com/samuelcolvin/pydantic/commit/dca98559d58b24627a8da543a688549b7c91b459#diff-1ef405a6b5a2fa9f20ea7e1f92e4c38eR468

**Comment by MrMrRobat** [comment]
The strange part is that tests were passing on windows somehow. This potentially means that pydantic could behave differently on this platform

**Comment by PrettyWood** [comment]
@samuelcolvin Do you want some help to investigate this matter?

**Comment by samuelcolvin** [comment]
This is preventing v1.6 from being released.

Any help on what's going wrong would be useful, I'll try and look later today.

**Comment by MrMrRobat** [comment]
I see this as a plan of investigating and fixing the issue:
* [X] ~Find why tests were broken~ — done in https://github.com/samuelcolvin/pydantic/pull/1682#issuecomment-653760235
* [ ] Find out why this changes didn't break tests on windows, fix if needed
* [ ] Restore expected behaviour while maintaining features introduced in #1545 and #1627

Unfortunately, I don't have IDE installed on windows to investigate, if someone could help with that, it would be great.

**Comment by PrettyWood** [comment]
So the real problem is that we have a "regression" with https://github.com/samuelcolvin/pydantic/pull/1545 where
```python
def test_conlist():
    class Model(BaseModel):
        v: conlist(int) = 'a'

    m = Model()
    assert m.v == 'a'
```
used to be valid with `1.5.1` because `validate_always` would not be set to `True` but now it does.
Do we actually need the `always=True` in `conlist` and recently added `conset` ?

**Comment by PrettyWood** [comment]
Meh I just tried on a windows 10 and python 3.8.2:
```python
tests\test_types.py:249 (test_constrained_set_default)
def test_constrained_set_default():
        class ConSetModelMax(BaseModel):
            v: conset(int) = {}
    
>       m = ConSetModelMax()
```
Would be nice to be able to connect via SSH on the windows 2019 server machine of github

**Comment by MrMrRobat** [comment]
Well, I looked at CI output closer and it noticed that tests actually failed, but CI did not detect it for some reason:
(and yeah, `test_env_file_custom_encoding` fails on windows ever since it was introduced: https://github.com/samuelcolvin/pydantic/runs/761260990)
```py
================================== FAILURES ===================================
________________________ test_env_file_custom_encoding ________________________

tmp_path = WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_env_file_custom_encoding0')

    @pytest.mark.skipif(not dotenv, reason='python-dotenv not installed')
    def test_env_file_custom_encoding(tmp_path):
        p = tmp_path / '.env'
        p.write_text('pika=p!�@', encoding='latin-1')
    
        class Settings(BaseSettings):
            pika: str
    
        with pytest.raises(UnicodeDecodeError):
>           Settings(_env_file=str(p))
E           Failed: DID NOT RAISE <class 'UnicodeDecodeError'>

tests\test_settings.py:557: Failed

________________________ test_constrained_set_default _________________________

    def test_constrained_set_default():
        class ConSetModelMax(BaseModel):
            v: conset(int) = {}
    
>       m = ConSetModelMax()

tests\test_types.py:254: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

__pydantic_self__ = ConSetModelMax(), data = {}, values = {}, fields_set = set()
validation_error = ValidationError(model='ConSetModelMax', errors=[{'loc': ('v',), 'msg': 'value is not a valid set', 'type': 'type_error.set'}])

    def __init__(__pydantic_self__, **data: Any) -> None:
        """
        Create a new model by parsing and validating input data from keyword arguments.
    
        Raises ValidationError if the input data cannot be parsed to form a valid model.
        """
        # Uses something other than `self` the first arg to allow "self" as a settable attribute
        if TYPE_CHECKING:
            __pydantic_self__.__dict__: Dict[str, Any] = {}
            __pydantic_self__.__fields_set__: 'SetStr' = set()
        values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
        if validation_error:
>           raise validation_error
E           pydantic.error_wrappers.ValidationError: 1 validation error for ConSetModelMax
E           v
E             value is not a valid set (type=type_error.set)

pydantic\main.py:346: ValidationError
=========================== short test summary info ===========================
FAILED tests/test_settings.py::test_env_file_custom_encoding - Failed: DID NO...
FAILED tests/test_types.py::test_constrained_set_default - pydantic.error_wra...
================= 2 failed, 1707 passed, 9 skipped in 27.38s ==================
mingw32-make: *** [Makefile:42: test] Error 1

**Comment by PrettyWood** [comment]
Thanks for checking @MrMrRobat. It's reassuring! I was afraid it was ok only on some windows systems.
So the next question is "How do we fix the CI on windows to **actually** fail?"

**Comment by samuelcolvin** [comment]
this is really weird, I've done quite a lot of digging but can't find anyone else having this problem with steps passing when `make` commands fail.

I think it must be some weird way gnu make and powershell are not working correctly together, but I can't find any clues about what's wrong.

**Comment by PrettyWood** [comment]
@samuelcolvin Don't you think we could ask someone from github (actions) to have a look ? Nothing has changed on pydantic side regarding the CI. The exit code is 1 and fails on local. And we are talking about `make`, which is used like in every CI and has been stable for so long. I don't know if something has changed on github action side though. Maybe a new windows OS or a new binary for gnu make ? I don't think you can connect via SSH on the machine to have a deeper look (like on CircleCI) but if you can maybe it's worth a try too?

**Comment by Kilo59** [comment]
@samuelcolvin @PrettyWood 
Could pydantic move away from `make` and start using `invoke`?
Then we don't have to rely on gnu make at all.
http://www.pyinvoke.org/

**Comment by PrettyWood** [comment]
Thanks for sharing @Kilo59. But I don't think the issue is to know if `make` should be used or not but first to understand why the CI fails. Samuel said it **could** come from `make` but nothing is sure! And anyway if there is an issue here, it might  well happen on other projects so it could be nice to dig into it and understand it. There are indeed **a lot** of projects that use `make` (personally I use it in all my python projects!)

**Comment by samuelcolvin** [comment]
@MrMrRobat @PrettyWood thank you both for your help. I'm working on the windows problem now on #1700

**Pull request merged**
