### PR TITLE
doc(schema): fix a callout

### PR DESCRIPTION
**Pull request by woodruffw**
First of all, thanks for Pydantic! It's an absolute pleasure to use.

## Change Summary

This just changes a small section to use Markdown-style boldfact for an important note. 

## Related issue number

None.

## Checklist

Not applicable (?)

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)

### CODE REVIEW

**Comment by StephenBrown2** [comment]
`!!! note` is actually the proper syntax for creating a callout that looks like this:
Screenshot 2021-04-01 at 13 23 56

However, as you've found, it's not working correctly in that spot:
Screenshot 2021-04-01 at 13 24 52


The proper fix I think would be to adjust the indentation so that the callout is detected, rather than an unformatted block, not to boldface the "note" text.

**Comment by woodruffw** [comment]
Oh, TIL! Okay, I'll experiment with that to get the callout working. Apologies for the churn.

**Comment by StephenBrown2** [comment]
> Oh, TIL! Okay, I'll experiment with that to get the callout working. Apologies for the churn.

No worries, happy to teach. Have you tried indenting it two spaces to see if it puts the note inline with the preceding paragraph? If that ends up not working, no big, but it'd be nice since it relates directly to the "`regex`: for string values" point.

**Comment by woodruffw** [comment]
> No worries, happy to teach. Have you tried indenting it two spaces to see if it puts the note inline with the preceding paragraph? If that ends up not working, no big, but it'd be nice since it relates directly to the "`regex`: for string values" point.

Trying that now!

**Comment by woodruffw** [comment]
That did the trick in my local tests:

**Comment by samuelcolvin** [comment]
The block of text still seems to be indented differently, is that intentional?

Also, I don't see any new bold text, am I missing something?

it might also be good to rebase to get the docs preview working properly.

**Comment by woodruffw** [comment]
> Also, I don't see any new bold text, am I missing something?

Sorry, the title's out of date -- I originally made it use boldface, but @StephenBrown2 informed me that `!!!` is actually the syntax for a callout. I'll update the PR title to reflect the current changes, which fix the callout so that it's actually rendered correctly.

I'll rebase this afternoon as well 🙂

**Comment by PrettyWood** [comment]
Duplicate of https://github.com/samuelcolvin/pydantic/pull/2544. I'll merge this one :)

**Comment by PrettyWood** [comment]
Thanks!

**Comment by woodruffw** [comment]
Thank you!

**Pull request merged**
