### PR TITLE
schema generation fix

### LINKED ISSUE #601: Schema generation sets null in definition if model used more than once
# Bug
When a custom model is referred more than once in the root model, its definition becomes **null** in the generated JSON Schema.

* OS: **?** Ubuntu  18
* Python version `import sys; print(sys.version)`: **?** 3.7.1
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **?** 0.28

```py
from typing import List
from pydantic import BaseModel


class Foo(BaseModel):
    count: int = 0
    size: float = None


class Bar(BaseModel):
    apple = 'x'
    banana = 'y'


class FooBar(BaseModel):
    foo: Foo
    bar: Bar


class FooFoosBar(BaseModel):
    foo: Foo
    foos: List[Foo]
    bar: Bar


print(FooBar.schema_json(indent=2))
print('------------------------------')
print(FooFoosBar.schema_json(indent=2))
```

Output
```
{
  "title": "FooBar",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "#/definitions/Foo"
    },
    "bar": {
      "$ref": "#/definitions/Bar"
    }
  },
  "required": [
    "foo",
    "bar"
  ],
  "definitions": {
    "Foo": {
      "title": "Foo",
      "type": "object",
      "properties": {
        "count": {
          "title": "Count",
          "default": 0,
          "type": "integer"
        },
        "size": {
          "title": "Size",
          "type": "number"
        }
      }
    },
    "Bar": {
      "title": "Bar",
      "type": "object",
      "properties": {
        "apple": {
          "title": "Apple",
          "default": "x",
          "type": "string"
        },
        "banana": {
          "title": "Banana",
          "default": "y",
          "type": "string"
        }
      }
    }
  }
}
------------------------------
{
  "title": "FooFoosBar",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "#/definitions/Foo"
    },
    "foos": {
      "title": "Foos",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Foo"
      }
    },
    "bar": {
      "$ref": "#/definitions/Bar"
    }
  },
  "required": [
    "foo",
    "foos",
    "bar"
  ],
  "definitions": {
    "Foo": null,
    "Bar": {
      "title": "Bar",
      "type": "object",
      "properties": {
        "apple": {
          "title": "Apple",
          "default": "x",
          "type": "string"
        },
        "banana": {
          "title": "Banana",
          "default": "y",
          "type": "string"
        }
      }
    }
  }
}
```

Expected Output
```
{
  "title": "FooBar",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "#/definitions/Foo"
    },
    "bar": {
      "$ref": "#/definitions/Bar"
    }
  },
  "required": [
    "foo",
    "bar"
  ],
  "definitions": {
    "Foo": {
      "title": "Foo",
      "type": "object",
      "properties": {
        "count": {
          "title": "Count",
          "default": 0,
          "type": "integer"
        },
        "size": {
          "title": "Size",
          "type": "number"
        }
      }
    },
    "Bar": {
      "title": "Bar",
      "type": "object",
      "properties": {
        "apple": {
          "title": "Apple",
          "default": "x",
          "type": "string"
        },
        "banana": {
          "title": "Banana",
          "default": "y",
          "type": "string"
        }
      }
    }
  }
}
------------------------------
{
  "title": "FooFoosBar",
  "type": "object",
  "properties": {
    "foo": {
      "$ref": "#/definitions/Foo"
    },
    "foos": {
      "title": "Foos",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Foo"
      }
    },
    "bar": {
      "$ref": "#/definitions/Bar"
    }
  },
  "required": [
    "foo",
    "foos",
    "bar"
  ],
  "definitions": {
    "Foo": {
      "title": "Foo",
      "type": "object",
      "properties": {
        "count": {
          "title": "Count",
          "default": 0,
          "type": "integer"
        },
        "size": {
          "title": "Size",
          "type": "number"
        }
      }
    },
    "Bar": {
      "title": "Bar",
      "type": "object",
      "properties": {
        "apple": {
          "title": "Apple",
          "default": "x",
          "type": "string"
        },
        "banana": {
          "title": "Banana",
          "default": "y",
          "type": "string"
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by wongpat**
## Related issue number

#601 

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `HISTORY.rst` has been updated
  * if this is the first change since a release, please add a new section
  * include the issue number or this pull request number `#<number>`
  * include your github username `@<whomever>`

### CODE REVIEW

**Comment by samuelcolvin** [comment]
@tiangolo please could you check. Presumably you included this code for a reason?

**Comment by wongpat** [comment]
Hi @samuelcolvin , not sure how to fix the issues in the CI server (related to `make lint` returning exit code 2?). I'm also surprised coverage went down considering I removed two lines of code. Let me know if there is any other info you need, and thank you for creating this library!

**Comment by samuelcolvin** [comment]
You have blank lines with whitespace as per the error message. 

The coverage will just be because not all tests passed, so coverage didn't get submitted for all cases.

**Comment by wongpat** [comment]
Looks like after fixing the formatting issues this PR regresses behavior regarding self-referencing models; will definitely hold off and see if @tiangolo has any insights. It looks like the structure of models with circular references is one level 'nested' from a regular model...maybe there's a better way to indicate such a model vs. this issue where the same model could be referenced in more than one field.

**Comment by tiangolo** [comment]
Thanks @wongpat ! Indeed, you found the bug! :tada: :bug: 

I'm proposing an alternative implementation here #621 , to avoid the hack of using `definitions` for something it was not intended to (hack that I introduced in the first PR :sweat_smile: )

**Comment by samuelcolvin** [comment]
replaced by #621

**Pull request closed without merging**
