### PR TITLE
Adding warning about Union order

### PR DESCRIPTION
**Pull request by djpugh**
## Change Summary

Adding warning about union order and initial definition (e.g. in third party libraries.)

## Related issue number
#2835 
#2092 should resolve this

## Checklist

* [x] Unit tests for the changes exist - n/a, just docs
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by djpugh** [comment]
please review

**Comment by djpugh** [comment]
This may not be needed depending on how docs are built and the release plan for #2092

**Comment by PrettyWood** [comment]
Hi @djpugh 
Sorry for coming back so late on all the PRs
I'm confident to have https://github.com/samuelcolvin/pydantic/pull/2092 in 1.9
I let this PR open but it will probably be closed if that's the case.
Feel free to have a look at #2092. Maybe some documentation you wrote can be backported

**Comment by djpugh** [comment]
Thanks @samuelcolvin, I've added a comment to the #2092 PR as well with a suggestion around the docs

**Comment by samuelcolvin** [comment]
closing since #2092 is merged, thank you for the work.

**Pull request closed without merging**
