### PR TITLE
allow custom get_field_config

### LINKED ISSUE #159: Add "camelCase" mode
Hello guys, 
At my company, our apis uses camelCase for all dictionnaire keys in json request and response bodies. That's a company guideline that came from the fact we communicate with several API's written in diverse languages. Since camelCase is the way variables are written in JS, we chose that.

This awesome library is quite useful for us. I'm using it, but before every *request* and every *response* I have to transform my dict.

Maybe you should support a ***camelCase mode*** just like [Serde](https://serde.rs/) does

### PR DESCRIPTION
**Pull request by samuelcolvin**
fix #159, by adding `get_field_config` classmethod to `Config`, also improves the way inheritance works for `Config` classes.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
@dnp1 hasn't responded about this after requesting it sadly.

However I think it would be useful so I'll merge in a few days unless anyone has any problems or improvement suggestions?

**Comment by alexandremjacques** [comment]
Does the documentation reflect this? Would be nice to have an example.

**Comment by ahmednafies** [comment]
is it possible to add a code example to documentation?

**Comment by samuelcolvin** [comment]
Pr welcome.

**Comment by harshithjv** [comment]
@samuelcolvin There is no mention for `get_field_config` in the document other than in changelog section. Its been almost 2 years since this feature has been published.

**Pull request merged**
